### ISSUE TITLE
A small question about the performance of FFA-Net in the paper

### ISSUE THREAD

**Issue by Owen718** [liuye123321/DMT-Net#1]
I have read your paper, and it's impressive work! But why the PSNR/SSIM on SOTS of FFA-Net in your paper is only 26.88/0.95? It's so confusing for me! As far as I know, the performance of FFA-Net on SOTS is great; the PSNR/SSIM should be more than 33/0.98 at least.

**Comment by liuye123321** [comment]
The training dataset used by us and FFA-Net method is different, so there will be different test results on SOTS.









发件人："Mr.Ye" ***@***.***>
发送日期：2021-09-03 17:54:11
收件人：liuye123321/DMT-Net ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[liuye123321/DMT-Net] A small question about the performance of FFA-Net in the paper (#1)

I have read your paper, and it's impressive work! But why the PSNR/SSIM on SOTS of FFA-Net in your paper is only 26.88/0.95? It's so confusing for me! As far as I know, the performance of FFA-Net on SOTS is great; the PSNR/SSIM should be more than 33/0.98 at least.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Owen718** [comment]
Okay, so why are the indicators of AOD-Net on SOTS in your paper exactly the same as those given in the FFA-Net paper? Is AOD-Net also trained on your training data set?

**Comment by liuye123321** [comment]
Sorry，these indicators of AOD-Net on SOTS we just followed 'Domain Adaptation for Image Dehazing(CVPR 2020)'.











发件人："Mr.Ye" ***@***.***>
发送日期：2021-09-10 13:22:30
收件人：liuye123321/DMT-Net ***@***.***>
抄送人：liuye123321 ***@***.***>,Comment ***@***.***>
主题：Re: [liuye123321/DMT-Net] A small question about the performance of FFA-Net in the paper (#1)

Okay, so why are the indicators of AOD-Net on SOTS in your paper exactly the same as those given in the FFA-Net paper? Is AOD-Net also trained on your training data set?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Owen718** [comment]
This means that the methods compared in the same table are not trained on the same data set, right? I think this is probably an unfair comparison. It is recommended that you supplement the indicators trained on the RESIDES dataset.

**Comment by Owen718** [comment]
Thank you very much for your reply. As I said before, you are doing valuable work.

**Comment by liuye123321** [comment]
You misunderstood me. 'Domain Adaptation for Image Dehazing' also proposed a new data set, and the results it showed should be trained on the dataset they proposed. The test result of FFA-Net on SOTS in our paper are trained also on the dataset 'Domain Adaptation for Image Dehazing'  proposed.







发件人："Mr.Ye" ***@***.***>
发送日期：2021-09-10 13:35:14
收件人：liuye123321/DMT-Net ***@***.***>
抄送人：liuye123321 ***@***.***>,Comment ***@***.***>
主题：Re: [liuye123321/DMT-Net] A small question about the performance of FFA-Net in the paper (#1)

This means that the methods compared in the same table are not trained on the same data set, right? I think this is probably an unfair comparison. It is recommended that you supplement the indicators trained on the RESIDES dataset.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Owen718** [comment]
Okay, I see what you mean.
